# File excludes
exclude:
- README.md


plugins: 
- jekyll-default-layout

# markdown type
markdown: redcarpet

theme: jekyll-theme-tactile

# site settings
url: 'https://srinjoychinargoswami.github.io/HCBiologysyllabusbank/'
basurl: ''
